apiVersion: apps/v1
kind: Deployment
metadata:
  name: workhorse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workhorse
  template:
    metadata:
      labels:
        app: workhorse
    spec:
      containers:
        - name: workhorse
          image: vvalev1980/workhorse:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/store-device-service
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SOURCE_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/market-master-data
            - name: SOURCE_DATASOURCE_USERNAME
              value: postgres
            - name: SOURCE_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_APPLICATION_NAME
              value: workhorse
            - name: SERVER_PORT
              value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: workhorse-service
spec:
  type: NodePort
  selector:
    app: workhorse
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
